name: CHRIS CERT TEST

on:
  pull_request:
    branches: [main]

jobs:
  chris-cert-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Is this thing on
        id: thing_on
        run: |
          echo "hi"

      - name: Write client auth certificate file
        id: write_client_auth_cert
        env:
          CLIENT_AUTH_CERT_BASE64_CONTENT: ${{ secrets.CODE_SIGNING_CERT_BASE64 }}
        run: |
          $p12Path = "cert.p12";
          $encodedBytes = [System.Convert]::FromBase64String($env:CLIENT_AUTH_CERT_BASE64_CONTENT);
          Set-Content $p12Path -Value $encodedBytes -AsByteStream;
          echo "p12_path=$p12Path" >> $ENV:GITHUB_OUTPUT

      - name: Check cert output
        run: |
          echo "CHecking the output of the write cert step"
          echo "${{ steps.write_client_auth_cert.outputs.p12_path }}"
          
