name: Homebrew Experiment

on:
  pull_request:
    branches: [main]

#env:
#  CARGO_TERM_COLOR: always
#  APP_NAME: 'momento-cli'
#  MAINTAINER: 'momentohq'
#  DESC: 'Official CLI for Momento Serverless Cache'

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
#    needs: [ release, publish-linux-assets, publish-mac-assets ]

    steps:
      - uses: actions/checkout@v3

      #      - name: Check out homebrew-tap
      #        uses: actions/checkout@v3
      #        with:
      #          fetch-depth: 0
      #          repository: momentohq/homebrew-tap
      #          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: update homebrew formulae
        run: |
          VERSION=0.25.6
          echo "Version is $VERSION"
          
          #LINUX_X86_64_URL="url "https://github.com/momentohq/momento-cli/releases/download/$VERSION/momento-cli-mac-silicon-homebrew-test-aarch64-macos.tar.xz""
          #INUX_AARCH64_SHA=${{ needs.publish-linux-assets.outputs.aarch64-sha }}
          
          
          #          git checkout -b formula/momento-cli/v${{ steps.semrel.outputs.version }}
          #          pushd Formula
          #            sed -i 's/sha256 ".*"/sha256 "${{ env.SHA }}"/g' momento-cli.rb
          #            sed -i 's/version ".*"/version "${{ steps.semrel.outputs.version }}"/g' momento-cli.rb
          #            sed -i 's/releases\/download\/.*\/archive-.*.tar.gz/releases\/download\/v${{ steps.semrel.outputs.version }}\/${{ env.ARCHIVE_FILE }}/g' momento-cli.rb
          #          popd
          #          git config user.email "momentobot@users.noreply.github.com"
          #          git config user.name "momentobot"
          #          git add .
          #          git commit -m "momento-cli ${{ steps.semrel.outputs.version }}"
          #          git push origin formula/momento-cli/v${{ steps.semrel.outputs.version }}
        shell: bash
